Feat/add fetch
thadjbullet/adidas-react pull request #11
Opened 2017-06-07 20:37 UTC by thadjbullet

Не сделано:
- Пагинация
- Фильтр по размерам
- Анимация

Короче то, что успел за 2 дня за компом. Костыльно, понимаю, но конца недели допилю канеш, хотя тебе уже не важно)
В остальном все сделано (даже вроде по заданию:)

2017-06-08 13:13 UTC, imevro requested changes

2017-06-08 13:13 UTC, evgenyrodionov commented on README.md
> +Install dependcies
covfefe

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Api.jsx
> +      Accept: '*/*',
Хуйня

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Api.jsx
> +const baseUrl = 'https://erodionov-adidas-fake-api.now.sh/v1';
Почемк файл называется Api.jsx? Это что, компонент?

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +import GetImageLink from '../../../components/GetImageLink';
Почему компонент называется как функция?

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    const images = this.props.item.images;
Дестракт

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +              ? GetImageLink(
Вынеси эту проверку в компонент

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +              ? GetImageLink(
Или функцию что у тебя там-то

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +    Get(url)
Get это компонент?

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +      .then(json => ({
Вынеси в функцию transformInputValues например

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +    this.state = { color: '#c5c5c5', item: {} };
Хуитем

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +import formatPrice from '../../components/FormatPrice';
что с неймингом-то

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +import formatPrice from '../../components/FormatPrice';
почему у тебя функция лежит в components и называется в паскалькейсе?

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +      {formatPrice(cost, '$')}
доллар есть в ответе сервера под currency, нахуй ты хардкодишь

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Filter/FilterSize.jsx
> +    this.state = { selectedId: 0 };
Айди или индекс

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Filter/FilterSize.jsx
> +  selectButton(selectedId) {
Императивный нейминг — говно

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/Filter/SizeButton.jsx
> +  handleOnClick() {
onClick либо handleClick, но не handleOnClick

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +/* eslint-disable global-require, quote-props */
Убирай нахуй

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      items: [],
хуитемс

2017-06-08 13:13 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      .catch(error => global.console.log('request failed', error));
какой глобал вообще

2017-06-08 13:13 UTC, evgenyrodionov commented on src/components/FormatPrice.jsx
> +  (price !== undefined ? `${currency}${(price / 100).toFixed(2)}` : '$0.00');
вообще не возвращай нихуя чем цену в нуле

2017-06-08 13:22 UTC, thadjbullet commented on README.md
> +Install dependcies
Че это?

2017-06-08 13:28 UTC, thadjbullet commented on src/Products/List/index.jsx
> +      .catch(error => global.console.log('request failed', error));
Eslint надо спрашивать

2017-06-12 13:35 UTC, imevro requested changes

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/Item/Gallery/BigImage.jsx
> +      item.images
убирай эти вычисления в пропах

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/Item/Gallery/BigImage.jsx
> +      item.images
внутри компонента ебашь проверки

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          {this.props.item.images
хуевая проверка, лучше нулевой массив по-умолчанию держи

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +  transformInputValues(json) {
зачем это в классе? Вынеси в функцию. Тебе еслинт об этом даже говорит

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +            this.setState({ item: this.transformInputValues(json) }),
ХУИТЕМ

Переименуй в продукт, камон

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  transformInputValues(json) {
у тебя повторяется, вынеси в отдельный хелпер

2017-06-12 13:35 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +            this.state.products.length !== 0
убрать вычисления из пропа

2017-06-12 13:35 UTC, evgenyrodionov commented on src/api.js
> +export default url => fetch(baseUrl + url);
пост, пут, делит ты как хуярить будешь

2017-06-12 13:35 UTC, evgenyrodionov commented on src/formatPrice.js
> +  switch (currency) {
Не свитч, а объект

2017-06-12 13:35 UTC, evgenyrodionov commented on src/formatPrice.js
> +      return `₽${price}`;
читай стандарты форматирования валют

2017-06-12 13:35 UTC, evgenyrodionov commented on src/formatPrice.js
> +      return `₽${price}`;
₽500 долбоебизм

2017-06-12 15:00 UTC, thadjbullet commented on src/Products/Item/Gallery/BigImage.jsx
> +      item.images
Это и есть компонент. Я учел прошлое замечание и вынес его отдельно.

2017-06-13 13:08 UTC, evgenyrodionov commented on README.md
> +Install dependcies
https://www.google.ru/search?q=dependcies&oq=dependcies&aqs=chrome..69i57j0l5.310j0j7&sourceid=chrome&ie=UTF-8

2017-06-13 13:15 UTC, imevro requested changes

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          index={this.state.selectedIndex}
index={selectedIndex}

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          {this.props.product.images &&
зачем, если можно products.images по-умолчанию сделать пустым массивом

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          {this.props.product.images &&
тогда эта проверка не будет нужна и .map будет проходиться (не проходиться) по пустому массиву

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +          ? <Product>
Тернарники выглядят как говно

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/Filter/FilterSize.jsx
> +  isSelected(id) {
Почему у тебя функция-обработчик-эвента называется как булеан свойство? втф?

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  handleFilter(filter) {
хэндлфильтр что

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      ? products.filter(item => item.sizes.includes(this.state.filter))
тернарники пиздец

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +      ? products.filter(item => item.sizes.includes(this.state.filter))
если у тебя будет нормальное исходное значение, то тебе не нужен будет тернарник

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        res.json().then(json =>
дестракт используй

2017-06-13 13:15 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +        res.json().then(json =>
почему res.json() не в api? нравится каждый раз писать?

2017-06-13 21:19 UTC, imevro requested changes
фикси оставшиеся комментарии, зачем пр прислал

2017-06-14 10:03 UTC, thadjbullet commented on src/Products/Item/Gallery/index.jsx
> +          index={this.state.selectedIndex}
Здесь я не понял, что ты хотел сказать.

2017-06-14 10:05 UTC, thadjbullet commented on src/Products/List/index.jsx
> +      ? products.filter(item => item.sizes.includes(this.state.filter))
Так тут проверка на наличие выделенного размера и фильтрация результатов. Но я переделал на if.

2017-06-14 10:09 UTC, thadjbullet commented
Убрал все тернарники.

2017-06-14 13:20 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          index={this.state.selectedIndex}
консистентность где

2017-06-14 13:21 UTC, imevro approved these changes

2017-06-14 13:21 UTC, merged