Feat/new product item
thadjbullet/adidas-react pull request #6
Opened 2017-05-22 19:20 UTC by thadjbullet

Оч интересует, правильно ли  я сделал галерею... Или совсем ахтунг и надо упрощать.

2017-05-22 19:29 UTC, imevro requested changes
Всё остальное вроде норм

2017-05-22 19:29 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    this.state = { id: 1, image: require('./shoes@3x.png') };
https://github.com/hmuriy1/adidas-shop-frontend/pull/8/files/295c2e835c06bb67e11fe5e91d181ebf2cea4caf#r117819746

2017-05-22 19:29 UTC, evgenyrodionov commented
Ну и вообще посмотри тот пр

2017-05-23 10:16 UTC, imevro requested changes

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/ColorButton.jsx
> +  changeColor() {
Зачем эта прокладка? Вызывай сразу this.props.changeColor где кликаешь

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/Image.jsx
> +  handleClick() {
Тоже самое, сделай лямбдой onClick={() => props.changeImage(props.id, props.source)}

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +  width: 80%;
Убирай, проценты зло

Плюс у тебя может быть вертикальная карточка, а не квадрат

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +  width: 80%;
Достаточно ограничить max-height конкретным значением в пикселях и всё

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +  static chooseImage(id) {
бля, откуда статик взялся? Зачем?

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    switch (id) {
В массив переделай, что это за хуйня!!!

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    const bigImage = GalleryItem.chooseImage(this.state.id);
Убирай, это импертивное говнище

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +  changeColor(newColor) {
Почему не просто color?

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +  changeColor(newColor) {
Зачем этот префикс new? Если метод называется changeColor, очевидно, параметром приходит новый цвет, а не какой-то другой

2017-05-23 10:16 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    switch (id) {
Делаешь массив из картинок, потом оперируешь его индексом И ВСЁ

2017-05-24 08:26 UTC, imevro requested changes

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    this.state = { id: 0 };
Это не айди, а индекс

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +  changeImage(num) {
num → id

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          <Image
Сделай мапом

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          <Image
По images

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +const Images = [
Это не компонент, соу с хуя ли с большой буквы

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          <Image
activeId и id упрости до isSelected={index === this.state.index}

2017-05-24 08:26 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +  changeColor(Color) {
ПОЧЕМУ С БОЛЬШОЙ БУКВЫ???????????????????????????????????? БЫЛО ЖЕ НОРМАЛЬНО????????????????????????????

2017-05-24 08:28 UTC, thadjbullet commented on src/Products/Item/index.jsx
> +  changeColor(Color) {
Линтер орет же

2017-05-24 11:52 UTC, imevro requested changes

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +    this.state = { index: 0 };
selectedIndex

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +  changeImage(id) {
index (и лучше разберись что значит ошибка еслинта)

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +              source={item}
src

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/Gallery/index.jsx
> +          {images.map((item, index) => (
item → image

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +  changeColor(color) {
handleChangeColor — ты ловишь эвент

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +      color,
А тут почему-то нормально сделал, лол

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +            <Options changeColor={this.changeColor} color={this.state.color} />
Почему changeColor дважды прокидываешь? Как в тайтле можно обновить цвет?

2017-05-24 11:52 UTC, evgenyrodionov commented on src/Products/Item/index.jsx
> +            <Options changeColor={this.changeColor} color={this.state.color} />
onChangeColor, кстати

2017-05-24 20:54 UTC, imevro approved these changes

2017-05-24 20:54 UTC, merged